name: Docker Release CI

on:
  create:
    tags:
      - '*'  # Triggers on any tag creation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag giteabot:latest  # Use lowercase here

  release:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag the Docker image
        run: docker tag giteabot:latest ghcr.io/${{ github.repository_owner }}/giteabot:${{ github.ref_name | toLowerCase() }}  # Ensure tag is lowercase

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/giteabot:${{ github.ref_name | toLowerCase() }}  # Ensure tag is lowercase

      - name: Output Docker Image URL
        run: echo "Docker Image URL - ghcr.io/${{ github.repository_owner }}/giteabot:${{ github.ref_name | toLowerCase() }}"  # Ensure tag is lowercase
