name: Docker Image CI

on:
  push:
    branches:
      - main  # Triggers on push to main branch
    tags:
      - '*'  # Triggers on any tag creation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag GiteaBot:latest

  push:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job
    if: startsWith(github.ref, 'refs/tags/')  # Only run this job if a tag is pushed

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag the Docker image
        run: docker tag GiteaBot:latest ghcr.io/${{ github.repository_owner }}/GiteaBot:${{ github.ref_name }}

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/GiteaBot:${{ github.ref_name }}

      - name: Output Docker Image URL
        run: echo "Docker Image URL: ghcr.io/${{ github.repository_owner }}/GiteaBot:${{ github.ref_name }}"
