name: Docker Release CI

on:
  create:
    tags:
      - '*'  # Triggers on any tag creation

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag giteabot:latest

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag the Docker image
        run: |
          lowercase_owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')  # Convert to lowercase
          docker tag giteabot:latest ghcr.io/${lowercase_owner}/giteabot:${{ github.ref_name }}

      - name: Push the Docker image
        run: |
          lowercase_owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')  # Convert to lowercase
          docker push ghcr.io/${lowercase_owner}/giteabot:${{ github.ref_name }}

      - name: Output Docker Image URL
        run: |
          lowercase_owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')  # Convert to lowercase
          echo "Docker Image URL - ghcr.io/${lowercase_owner}/giteabot:${{ github.ref_name }}"
