name: Docker Build CI

on:
  push:
    branches: 
      - '**'  # Triggers on any push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag GiteaBot:latest
